### ISSUE TITLE
Helm charts does not support k8s >1.22

### ISSUE THREAD

**Issue by serhat-ozkara** [uselagoon/lagoon-service-images#1]
Charts under https://github.com/uselagoon/lagoon-service-images/tree/main/kubectl-build-deploy-dind/helmcharts such as
https://github.com/uselagoon/lagoon-service-images/blob/main/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/ingress.yaml
still use apiVersion: networking.k8s.io/v1beta1

**Comment by tobybellwood** [comment]
Hi @serhat-ozkara - these images are not currently maintained - instead, use the ones in uselagoon/lagoon - which have just been updated to suppor Kubernetes 1.22, and will be released in the next couple of days.

This repo is a point-in-time fork of some of the lagoon services that have no interdependencies on the rest of the lagoon-core services. We are intending to create it as it's own entity, but are not currently working on it. Apologies for not making it clearer in the repo description.

**Comment by tobybellwood** [comment]
closing as handled
